name : My First Workflow

on: push

jobs: 
    first_job: 
        runs-on: unbuntu-latest
        steps:
            - name: Welcome message
              run: echo "My First GitHub Actions Job"


            - name: List file
              run: latest

            - name: Read file
              run: cat README.md