name : My First Workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read File
          run: |
           echo "My First GitHub Actions Job"
           ls -ltra
           cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a Dragon .....Rarrr" >> dragon.txt
        # - name: List file
        #   run: ls

        # - name: Read files
        #   run: cat README.md