name : Generate ASCII Artwork

on: push

jobs: 
    build_job_1: 
        runs-on: ubuntu-latest
        steps:

        - name: Install cowsay lib
          run: sudo apt-get install -y cowsay
        
        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run For cover, I'm a dragon" >> dragon.txt

        - name: Upload Dragon txt file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    test_job_2:
        needs: [build_job_1]
        runs-on: ubuntu-latest
        steps:

        - name:  Download Dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:

        - name:  Download Dragon text file
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file

        - name: Read File 
          run: cat dragon.txt

        - name: Deploy 
          run: echo Deploying ... ... .

       
        