name : Generate ASCII Artwork

on: push

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List Repo File
          run: ls -ltra

        - name: Execute the Shell Script
          run: |
              chmod +x ascii_job.sh 
              ./ascii_job
       
        