name: Workflow Filters and Activities

on: 
  workflow_dispatch:
#   schedule:              
#         - cron: "*/59 * * * *"
  push:
    # branches-ignore:
    #     - feature/*     #single path feature/payment
    #     - test/**       #mutlile path test/images/v1
    branches:
        - main
        - '!feature/*'   #ignoring pushing to any branch name starting with feature using !
  pull_request:
    types:
        - opened
        - closed
    paths-ignore:       # workflow will only run when a pull request that includes a change on any file other than README.md
        - README.md
    branches:
        - main


jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for event type - ${{github.event_name}}
